### ISSUE TITLE
Git hub i am very taierd i dont sleep  along time in i srael 8:00 am thanks

### ISSUE THREAD

**Issue by whteBaerd** [ianheggie/rbenv-env#6]
I wont to thank you but if you wont that o anderstend i need tranceleion to ebrew thanks

**Comment by ianheggie** [comment]
I have not thought of making my programs multi lingual because I only understand English and I don't trust google to translate.

Good translations especially to languages like Hebrew are hard to code. Though I love God and His word, I only read English. For example Psalms 139:17-18 (NJKV) translated reads  

17 How precious also are Your thoughts to me, O God! How great is the sum of them!
18 If I should count them, they would be more in number than the sand; When I awake, I am still with You.

All the best
